#!/sbin/busybox sh

STEP=BUS_MIF_VOLT_`echo $2`

if [ -z $3 ]; then
	evalcmd='eval echo \$$STEP'
	if [ "a`eval $evalcmd`" == "a" ]; then
		while read FREQ VOLT; do
			if [ "a`eval $evalcmd`" == "a" ]; then
				S_FREQ=`echo $FREQ | cut -c 1-3`
				if [ ${S_FREQ} -eq $2 ]; then
					eval $STEP=$VOLT
					echo $STEP=$VOLT >> $DEFAULT_PROFILE
					break
				fi
			fi
		done < /sys/devices/system/cpu/busfreq/mif_volt_table
	fi
else
	eval $STEP=$3

	if [ "$CONTROLSWITCH_BUS" == "on" -o "$CONFIG_BOOTED" == true ]; then
		while read FREQ VOLT; do
			S_FREQ=`echo $FREQ | cut -c 1-3`
			if [ $S_FREQ -eq $2 ]; then
				echo $FREQ $3 > /sys/devices/system/cpu/busfreq/mif_volt_table
			fi
		done < /sys/devices/system/cpu/busfreq/mif_volt_table
	fi
fi

eval echo \$$STEP
