#!/system/bin/sh
#Headphone volume
#Change headphone volume:
#Vol 50 (default, stock)

echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound
echo "50 50" > /sys/class/misc/boeffla_sound/headphone_volume
