#!/system/bin/sh
#Speaker tuning
#Improve sound of speaker for media playback
#Off (default)

echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound
echo 0 > /sys/class/misc/boeffla_sound/speaker_tuning
