#!/system/bin/sh
#Microphone sensivity general
#Set microphone sensivity for recording purposes
#10.5db

echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound
echo 18 > /sys/class/misc/boeffla_sound/mic_level_general
