#!/system/bin/sh
#Microphone sensivity general
#Set microphone sensivity for recording purposes
#25.5db (default)

echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound
echo 28 > /sys/class/misc/boeffla_sound/mic_level_general
