#!/sbin/sh
#USB MASS STORAGE MODE (UMS)
#ENABLE/DISABLE UMS MODE for external sdcard :
#Off (Default)

#AOSP 4.4.2

USB_GADGET="/sys/devices/platform/s3c-usbgadget/gadget/lun0/file"

/sbin/busybox echo "" > $USB_GADGET
/sbin/busybox sleep 2
/system/bin/vold
/sbin/busybox sleep 2
/system/bin/setprop persist.sys.usb.config mtp,adb
