#!/system/bin/sh
#Governor
#Change CPU governor:
#ZZMoove gov-default

# switch governor
echo "zzmoove" >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
/sbin/busybox sleep 2

# zzmoove governor default settings (also hardcoded):
echo 1 > /sys/devices/system/cpu/cpufreq/zzmoove/profile_number
