#!/system/bin/sh
#Governor
#Change CPU governor:
#ZZMoove ZaneZ-Moderate

# switch governor
echo "zzmoove" >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
/sbin/busybox sleep 2

echo 6 > /sys/devices/system/cpu/cpufreq/zzmoove/profile_number
