#!/system/bin/sh
#Governor
#Change CPU governor:
#ZZMoove - yank

# switch governor
echo "zzmoove" >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
/sbin/busybox sleep 2

# zzmoove governor settings (yank555.lu):
echo "180000" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate
echo "1" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_down_factor
echo "80" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold
echo "70" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug1
echo "80" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug2
echo "98" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug3
echo "40" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold
echo "55" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug1
echo "65" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug2
echo "75" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug3
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/ignore_nice_load
echo "10" >/sys/devices/system/cpu/cpufreq/zzmoove/freq_step
echo "65" >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up
echo "100" >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up_sleep
echo "4" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate_sleep_multiplier
echo "98" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_sleep
echo "55" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_sleep
echo "1	" >/sys/devices/system/cpu/cpufreq/zzmoove/hotplug_sleep
