#!/system/bin/sh
#Governor
#Change CPU governor:
#ZZMoove - optimized

# switch governor
echo "zzmoove" >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
/sbin/busybox sleep 2

# zzmoove governor settings optimized (between battery and performance)
echo "45000" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate
echo "1" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_down_factor
echo "67" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold
echo "52" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/ignore_nice_load
echo "5" >/sys/devices/system/cpu/cpufreq/zzmoove/freq_step
echo "75" >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up

# hotplug up threshold per core ("smoother" hotplugging)
echo "68" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug1
echo "78" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug2
echo "88" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug3

# hotplug down threshold per core ("smoother" hotplugging)
echo "45" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug1
echo "55" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug2
echo "65" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug3

# sampling rate at suspend (screen off)
echo "2" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate_sleep_multiplier

# up/down threshold at suspend (screen off)
echo "55" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_sleep
echo "98" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_sleep

# smooth up scaling only at 100% load at suspend (screen off)
echo "100" >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up_sleep

# use only one core at suspend (screen off) previously set settings will be restored at awake (screen on)
echo "1" >/sys/devices/system/cpu/cpufreq/zzmoove/hotplug_sleep
