#!/system/bin/sh
#CPU Max Frequency
#Change CPU maximum scaling:
#1704 MHz

echo "1704000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

# Display confirmation window

rm /sdcard/boeffla_twk_dlg_helper

am start -a android.intent.action.MAIN -e message "WARNING: On unstability resulting in reboots deselect this immediately" -e title "1.7 GHz CPU OC WARNING" -e okstyle "I ACKNOWLEDGE :)" -n hm.agni.control.dialog.helper/.AGNiControlDialogActivity
	
while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

rm /sdcard/boeffla_twk_dlg_helper

