#!/system/bin/sh
#GPU Threshold
#Change MALI 400MP GPU Frequency Threshold:
#Battsave

# Threshold0-1/up-down: 50% 42%
# Threshold1-2/up-down: 70% 65%
# Threshold2-3/up-down: 70% 65%
# Threshold3-4/up-down: 70% 65%

echo "50% 42% 70% 65% 70% 65% 70% 65%" > /sys/class/misc/gpu_control/gpu_clock_control

