#!/system/bin/sh
#GPU Threshold
#Change MALI 400MP GPU Frequency Threshold:
#More Battsave

# Threshold0-1/up-down: 70% 62%
# Threshold1-2/up-down: 90% 85%
# Threshold2-3/up-down: 90% 85%
# Threshold3-4/up-down: 90% 85%    #MALI r3p2 Derteufel default

echo "70% 62% 90% 85% 90% 85% 90% 85%" > /sys/class/misc/gpu_control/gpu_clock_control

