#!/system/bin/sh
#GPU Threshold
#Change MALI 400MP GPU Frequency Threshold:
#Normal (default)

# Threshold0-1/up-down: 40% 32%
# Threshold1-2/up-down: 60% 55%
# Threshold2-3/up-down: 60% 55%
# Threshold3-4/up-down: 60% 55%

echo "40% 32% 60% 55% 60% 55% 60% 55%" > /sys/class/misc/gpu_control/gpu_clock_control
