#!/sbin/busybox sh
#USB Charge Rate
#Set charging rate when connected to USB
#(disable USB charging)

echo 0 > /sys/devices/platform/samsung-battery/sdp_chrg_curr
echo 0 > /sys/devices/platform/samsung-battery/cdp_chrg_curr
