#!/system/bin/sh
#AGNi preloadSWAP 512MB
#Enable or disable preloadSWAP with 2nd priority:
#On

umount /preload
mount -o rw,remount /
rmdir /preload
mount -o ro,remount /
mkswap /dev/block/mmcblk0p10
/sbin/busybox swapon -p 2 /dev/block/mmcblk0p10
echo 30 > /proc/sys/vm/swappiness
sleep 2
