#!/sbin/sh
#AGNi preloadSWAP 512MB
#Enable or disable preloadSWAP with 2nd priority:
#Off (default)

umount /preload
mount -o rw,remount /
mkdir /preload
mount -o ro,remount /
swapoff /dev/block/mmcblk0p10 && /sbin/busybox mke2fs /dev/block/mmcblk0p10 && /sbin/make_ext4fs /dev/block/mmcblk0p10 && mount -t ext4 -o nosuid,nodev,noatime,nodiratime,discard /dev/block/mmcblk0p10 /preload;
