#!/system/bin/sh
#AGNi preloadSWAP 512MB
#Enable or disable preloadSWAP with 2nd priority:
#On

PRELOAD="/dev/block/mmcblk0p10"

if [ `/system/xbin/busybox uname -r | /system/xbin/busybox grep India` ];
	then
	/sbin/busybox umount /preload
	/sbin/busybox mount -o rw,remount /
	/sbin/busybox rmdir /preload
	/sbin/busybox mount -o ro,remount /
	/sbin/busybox mkswap $PRELOAD
	/sbin/busybox swapon -p 2 $PRELOAD
	/sbin/busybox echo 30 > /proc/sys/vm/swappiness
	/sbin/busybox sleep 2
	else
	/system/xbin/busybox umount /preload
	/system/xbin/busybox mount -o rw,remount /
	/system/xbin/busybox mkdir /preload
	/system/xbin/busybox mount -o ro,remount /
	/system/xbin/busybox swapoff $PRELOAD
	/system/bin/mke2fs $PRELOAD
	/system/bin/make_ext4fs $PRELOAD
	/system/xbin/busybox mount -t ext4 -o nosuid,nodev,noatime,nodiratime,discard $PRELOAD /preload
fi
