#!/sbin/busybox sh
#Touchboost
#Enable or disable Touchboost:
#700 MHz

echo "1" > /sys/class/misc/touchboost_switch/touchboost_switch
echo "700000" > /sys/class/misc/touchboost_switch/touchboost_freq

