#!/sbin/busybox sh
#FRANDOM RNG
#Use frandom kernel entropy generator (needs reboot) :
#off (default)

# Display confirmation window

if [ ! -f /system/etc/init.d/*bkfrandomlagfix_010-off_default ]; then

	rm /sdcard/boeffla_twk_dlg_helper
	
	am start -a android.intent.action.MAIN -e message "FRANDOM RNG will not be used on next reboot !" -e title "Frandom" -e okstyle "Ok" -n hm.agni.control.dialog.helper/.AGNiControlDialogActivity
	
	while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
	do
	  /sbin/busybox sleep 1
	done
	
	rm /sdcard/boeffla_twk_dlg_helper

fi

