#!/sbin/busybox sh
#TOUCHKEY LIGHTING SCENARIO
#Select hardware touch keys lighting scenario :
#Always Off

echo 1 > /sys/class/sec/sec_touchkey/touch_led_handling
echo 1 > /sys/class/sec/sec_touchkey/force_disable
