#!/sbin/busybox sh
#TOUCHKEY LIGHTING SCENARIO
#Select hardware touch keys lighting scenario :
#Lights up on h/w keys or screen touch

chmod 666 /sys/class/sec/sec_touchkey/force_disable
echo 0 > /sys/class/sec/sec_touchkey/force_disable
chmod 444 /sys/class/sec/sec_touchkey/force_disable

echo 1 > /sys/class/sec/sec_touchkey/touch_led_on_screen_touch

