#!/sbin/busybox sh
#TOUCHKEY LIGHTING SCENARIO
#Select hardware touch keys lighting scenario :
#Lights up on h/w keys or screen touch

echo 1 > /sys/class/sec/sec_touchkey/touch_led_handling # KERNEL MODE
echo 0 > /sys/class/sec/sec_touchkey/force_disable
echo 1 > /sys/class/sec/sec_touchkey/touch_led_on_screen_touch
