#!/system/bin/sh

# Check if we're running as root
if [ `whoami 2>&1 | grep -i "root" | wc -l` -eq 0 ] && [ `whoami 2>&1 | grep -i "uid 0" | wc -l` -eq 0 ]; then
	echo "Sorry but you need to execute this script as root"
	exit 1
fi

ADDEV="/system/archidroid/dev"
sysrw

if [ -e $ADDEV/ADBLOCK_ENABLED ]; then
	chattr -i /system/etc/hosts
	rm -f $ADYSYS/HOSTS_LOCKED
	touch $ADSYS/HOSTS_UNLOCKED
	mv $ADDEV/ADBLOCK_ENABLED $ADDEV/ADBLOCK_DISABLED
	echo "Adblock has been disabled"
elif [ -e $ADDEV/ADBLOCK_DISABLED ]; then
	echo "# ArchiDroid Hosts File
# This file has been blocked from editing for a very good reason
# ArchiDroid has built-in AdBlock, if that's what you're searching for
# Please DO NOT edit this file
# Use /system/archidroid/etc/hosts file instead

127.0.0.1	localhost	localhost.localdomain
127.0.0.1	loopback	loopback.localdomain
127.0.0.1	android
::1		localhost6	localhost6.localdomain
::1		loopback6	loopback6.localdomain
255.255.255.255	broadcasthost" > /system/etc/hosts
	chattr +i /system/etc/hosts
	rm -f $ADYSYS/HOSTS_UNLOCKED
	touch $ADSYS/HOSTS_LOCKED
	mv $ADDEV/ADBLOCK_DISABLED $ADDEV/ADBLOCK_ENABLED
	echo "Adblock has been enabled"
else
	sysro
	echo "Could not find actual adblock status!"
	exit 1
fi

sysro
ARCHIDROID_INIT "RELOAD" "ADBLOCK"
exit 0