#!/system/etc/CrossBreeder/busybox sh 
set +e

/system/etc/CrossBreeder/busybox mount -o rw,remount,noatime,nodiratime /system

rm /system/etc/CrossBreeder/BYPASS_ISP 2>/dev/null

/system/etc/CrossBreeder/busybox mount -o ro,remount,noatime,nodiratime /system

killall -9 dnsmasq_dhcp

/system/etc/CrossBreeder/zzCHECK_NET_DNS RUN &

echo DONE. Your local ISP is now enabled.
