#!/system/etc/CrossBreeder/busybox sh 
set +e

/system/etc/CrossBreeder/busybox mount -o rw,remount,noatime,nodiratime /system

touch /system/etc/CrossBreeder/BYPASS_ISP 2>/dev/null

/system/etc/CrossBreeder/busybox mount -o ro,remount,noatime,nodiratime /system

killall -9 dnsmasq_dhcp

/system/etc/CrossBreeder/zzCHECK_NET_DNS RUN &

echo DONE. Local ISP DNS servers will not be queried.
echo NOTE - This may take slightly longer for the DNS takeover to happen.
