#!/system/etc/CrossBreeder/busybox sh 
set +e

/system/etc/CrossBreeder/busybox mount -o rw,remount,noatime,nodiratime /system

rm /system/etc/CrossBreeder/STOP_TWEAKING_GOVERNOR 2>/dev/null
touch /system/etc/CrossBreeder/START_TWEAKING_GOVERNOR 2>/dev/null

/system/etc/CrossBreeder/busybox mount -o ro,remount,noatime,nodiratime /system

/system/etc/CrossBreeder/zzCrossBreeder FORCE &

echo DONE. Governor tweaks are enabled and in effect.
