#!/system/etc/CrossBreeder/busybox sh 
set +e

/system/etc/CrossBreeder/busybox mount -o rw,remount,noatime,nodiratime /system

rm /system/etc/CrossBreeder/STOP_ADBLOCK 2>/dev/null

touch /system/etc/CrossBreeder/START_ADBLOCK 2>/dev/null

#mv /system/etc/hosts /system/etc/hosts.CBBAK 2>/dev/null
if [ ! -f /system/etc/hosts.CBBAK ]; then
  /system/etc/CrossBreeder/busybox cp -a -f /system/etc/hosts /system/etc/hosts.CBBAK
fi
/system/etc/CrossBreeder/busybox cp -a -f /system/etc/CrossBreeder/hosts /system/etc/hosts 2>/dev/null

/system/etc/CrossBreeder/busybox mount -o ro,remount,noatime,nodiratime /system

killall -9 dnrd.10053

/system/etc/CrossBreeder/zzCHECK_NET_DNS &

echo DONE. Adblock is enabled now using around 3 MB of RAM.
