#!/system/bin/sh

ADSTATUS="/dev/ARCHIDROID_DNSDAEMON_STATUS"

# Make sure that we're running in the background
if [ "$1" != "background" ]; then
	sh $0 "background" $@ &
	exit 0
fi

echo $$ > $ADSTATUS
DNS1=$(getprop net.dns1)

while [ $(cat $ADSTATUS) == $$ ]; do
	CURDNS1=$(getprop net.dns1)
	if [ "$CURDNS1" != "$DNS1" ]; then
		DNS1="$CURDNS1"
		ARCHIDROID_INIT "RELOAD" "ADBLOCK" "DNSCHANGE"
		sleep 5
	fi
	sleep 1
done

exit 0