#!/system/bin/sh

#     _             _     _ ____            _     _
#    / \   _ __ ___| |__ (_)  _ \ _ __ ___ (_) __| |
#   / _ \ | '__/ __| '_ \| | | | | '__/ _ \| |/ _` |
#  / ___ \| | | (__| | | | | |_| | | | (_) | | (_| |
# /_/   \_\_|  \___|_| |_|_|____/|_|  \___/|_|\__,_|
#
# Copyright 2014 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ADMOUNTED() {
	return "$(mount | grep -qi "$1"; echo $?)"
}

ADTWEAK() {
	# $1 - what we're changing
	# $2 - to what we're changing
	local CURRENT="$(cat "$1")"
	if [[ "$CURRENT" = "$2" ]]; then
		echo "ADTWEAK: Value of $1 is already set to $CURRENT"
	else
		echo "$2" > "$1"
		echo "ADTWEAK: Tweaked $1 value from $CURRENT to $2"
	fi
}

ADCRON() {
	# $1 - Cron file to notify
	# $2 - Optional content
	if [[ -f "$1" ]]; then
		rm -f "$1"
	fi
	echo "$2" > "$1"
}

ADCRONWAIT() {
	ADCRON "$@"
	sleep 1
}

ADSTOP() {
	case "$1" in
		"ALL")
			ADSTOP "HAVEGED"
			ADSTOP "FRANDOM"
			ADSTOP "ADBLOCK"
			ADSTOP "CRON"
			ADSTOP "TMPFS"
			;;
		"ADBLOCK")
			ADSTOP "archidroid_dnsmasq"
			ADSTOP "archidroid_dnsproxy2"
			ADSTOP "archidroid_pixelserv"
			ndc resolver flushdefaultif >/dev/null 2>&1 # Flush DNS Cache
			;;
		"FRANDOM")
			# Generic check if we're not doing something harmful
			if [[ -c /dev/urandom.orig && -c /dev/random.orig ]]; then
				rm -f /dev/urandom && mv /dev/urandom.orig /dev/urandom
				rm -f /dev/random && mv /dev/random.orig /dev/random
			fi
			;;
		"HAVEGED")
			ADSTOP "archidroid_haveged"
			;;
		"CRON") ADCRON "$ADCRONSTATUS" "STOPPED" ;;
		"TMPFS")
			if ADMOUNTED "$ADTMPFS"; then
				umount "$ADTMPFS"
			fi
			;;
		archidroid_haveged)
			ADCRONWAIT "$INTERNAL_EVENTS_DIR/MONITOR_STOP_HAVEGED"
			kill "$(pidof archidroid_haveged)" >/dev/null 2>&1
			;;
		archidroid_dnsmasq)
			ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_STOP_DNSDAEMON"
			ADCRONWAIT "$INTERNAL_EVENTS_DIR/MONITOR_STOP_DNSMASQ"
			kill "$(pidof archidroid_dnsmasq)" >/dev/null 2>&1
			;;
		archidroid_dnsproxy2)
			ADCRONWAIT "$INTERNAL_EVENTS_DIR/MONITOR_STOP_DNSPROXY2"
			kill "$(pidof archidroid_dnsproxy2)" >/dev/null 2>&1
			;;
		archidroid_pixelserv)
			ADCRONWAIT "$INTERNAL_EVENTS_DIR/MONITOR_STOP_PIXELSERV"
			kill "$(pidof archidroid_pixelserv)" >/dev/null 2>&1
			;;
		*) kill "$(pidof "$1")" >/dev/null 2>&1
	esac
}

ADSTART() {
	case "$1" in
		"ALL")
			ADSTART "TMPFS"
			ADSTART "CRON"
			ADSTART "HAVEGED"
			ADSTART "FRANDOM"
			ADSTART "ADBLOCK"
			;;
		"ADBLOCK")
			ADSTART "archidroid_dnsmasq"
			ADSTART "archidroid_dnsproxy2"
			ADSTART "archidroid_pixelserv"
			;;
		"FRANDOM")
			if [[ "$FRANDOM" -eq 1 ]]; then
				echo "INFO: Activating frandom!"
				if [[ ! -c /dev/frandom ]]; then
					echo "FRANDOM: frandom device not found, searching for frandom.ko kernel module..."
					for FRANDOMPATH in "/system/lib/modules" "/system/modules" "/lib/modules" "/modules"; do
						if [[ -f "$FRANDOMPATH/frandom.ko" ]]; then
							echo "FRANDOM: Loading frandom using $FRANDOMPATH/frandom.ko!"
							insmod "$FRANDOMPATH/frandom.ko"
							sleep 1
							break
						fi
					done
				fi
				if [[ -c /dev/frandom ]]; then
					echo "FRANDOM: frandom device found, activating erandom!"
					if [[ ! -c /dev/urandom.orig && ! -c /dev/random.orig ]]; then
						mv /dev/urandom /dev/urandom.orig &&
						ln /dev/erandom /dev/urandom &&
						chmod 666 /dev/urandom

						mv /dev/random /dev/random.orig &&
						ln /dev/frandom /dev/random &&
						chmod 666 /dev/random
						echo "FRANDOM: Activated!"
					else
						echo "FRANDOM: It looks like frandom has been already loaded"
					fi
				else
					echo "FRANDOM: frandom device not found after loading, it looks like it's not provided by your kernel or failed to load!"
				fi
			else
				echo "INFO: Frandom has been disabled"
			fi
			;;
		"HAVEGED")
			ADSTART "archidroid_haveged"
			;;
		"CRON")
			echo "INFO: Activating ArchiDroid Cron!"
			setsid ARCHIDROID_CRON "background" &
			;;
		"TMPFS")
			if ! ADMOUNTED "$ADTMPFS"; then
				mkdir -p "$ADTMPFS"
				mount -t tmpfs tmpfs "$ADTMPFS"
			fi
			;;
		"archidroid_dnsmasq")
			if [[ "$ADBLOCK" -eq 1 ]]; then
				sysrw
				if [[ ! -f /system/archidroid/etc/hosts ]]; then
					if [[ -f "$ADDEV/ADBLOCK_USE_ADAWAY_HOSTS" ]]; then
						ln -s /system/archidroid/etc/hosts_adaway /system/archidroid/etc/hosts
					elif [[ -f "$ADDEV/ADBLOCK_USE_MOAB_HOSTS" ]]; then
						ln -s /system/archidroid/etc/hosts_moab /system/archidroid/etc/hosts
					else
						echo "WARNING: No adblock hosts mode specified!"
					fi
				else
					if [[ -f "$ADDEV/ADBLOCK_USE_ADAWAY_HOSTS" ]]; then
						if [[ "$(readlink /system/archidroid/etc/hosts)" != "/system/archidroid/etc/hosts_adaway" ]]; then
							rm -f /system/archidroid/etc/hosts &&
							ln -s /system/archidroid/etc/hosts_adaway /system/archidroid/etc/hosts
						fi
					elif [[ -f "$ADDEV/ADBLOCK_USE_MOAB_HOSTS" ]]; then
						if [[ "$(readlink /system/archidroid/etc/hosts)" != "/system/archidroid/etc/hosts_moab" ]]; then
							rm -f /system/archidroid/etc/hosts &&
							ln -s /system/archidroid/etc/hosts_moab /system/archidroid/etc/hosts
						fi
					else
						echo "ERROR: No adblock hosts mode specified!"
					fi
				fi
				sysro
				if [[ ! -f "$ADTMPFS/resolv.conf" ]]; then
					cp -p /system/etc/resolv.conf "$ADTMPFS/resolv.conf"
				fi
				local EXTRA="--all-servers -x $ADTMPFS/DNSMASQ.PID"
				if [[ "$ADBLOCKLOCALDNSES" -eq 1 ]]; then
					if [[ "$ADBLOCKSTRICTORDER" -eq 1 ]]; then
						echo "ADBLOCK: Strict order enabled!"
						EXTRA+=" --strict-order"
					fi
					echo "ADBLOCK: Including local DNSes!"
					if [[ -d "$INTERNAL_EVENTS_DIR" ]]; then
						ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_START_DNSDAEMON"
					else
						(sleep 10; ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_START_DNSDAEMON") &
					fi
				else
					if [[ -d "$INTERNAL_EVENTS_DIR" ]]; then
						ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_STOP_DNSDAEMON"
					fi
					cp "/system/etc/resolv.conf" "$ADTMPFS/resolv.conf"
				fi
				echo "ADBLOCK: Activated archidroid_dnsmasq - local DNS server on 127.0.0.1:53, forwarding clean non-blocked traffic to specified DNS servers"
				archidroid_dnsmasq $EXTRA -C /system/archidroid/etc/dnsmasq.conf # Yes, we must break on spaces in this case
				ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_START_DNSMASQ"
			fi
			;;
		"archidroid_dnsproxy2")
			if [[ "$ADBLOCK" -eq 1 ]]; then
				echo "ADBLOCK: Activated archidroid_dnsproxy2 - local proxy server, forwarding all DNS traffic to 127.0.0.1:53"
				archidroid_dnsproxy2 -w 127.0.0.1 &
				ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_START_DNSPROXY2"
			fi
			;;
		"archidroid_pixelserv")
			if [[ "$ADBLOCK" -eq 1 ]]; then
				echo "ADBLOCK: Activated archidroid_pixelserv - local web server on 127.0.0.1:80, responding with NULLGIF"
				archidroid_pixelserv 127.0.0.1 >/dev/null 2>&1 &
				ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_START_PIXELSERV"
			fi
			;;
		"archidroid_haveged")
			if [[ "$HAVEGED" -eq 1 ]]; then
				echo "INFO: Activating haveged!"
				local ENTROPY="1024" # Default: 128, Linux: 896, Max: 4096 - We want to make it high enough, but with considering battery life as well
				ADTWEAK "/proc/sys/vm/dirty_expire_centisecs" "1000"
				ADTWEAK "/proc/sys/vm/dirty_writeback_centisecs" "500"

				if [[ -c /dev/random.orig ]]; then
					mv /dev/random /dev/random.TEMP &&
					mv /dev/random.orig /dev/random &&
					archidroid_haveged -p "$ADTMPFS/HAVEGED.PID" -w "$ENTROPY" >/dev/null 2>&1 &&
					sleep 2 && # Let's give haveged some time to initialize
					mv /dev/random /dev/random.orig &&
					mv /dev/random.TEMP /dev/random
				else
					archidroid_haveged -p "$ADTMPFS/HAVEGED.PID" -w "$ENTROPY" >/dev/null 2>&1 &&
					sleep 2 # Let's give haveged some time to initialize
				fi

				echo "INFO: Activated archidroid_haveged - HArdware Volatile Entropy Gathering and Expansion Daemon, regenerating kernel's entropy pool"
				echo "HAVEGED: Entropy levels: Android default: 128, Linux: 896, Max: 4096"
				echo "HAVEGED: ArchiDroid entropy set to: $ENTROPY. Available entropy can't get below this level"
				echo "HAVEGED: Current available entropy: $(cat /proc/sys/kernel/random/entropy_avail)"
				ADCRON "$INTERNAL_EVENTS_DIR/MONITOR_START_HAVEGED"
			fi
			;;
	esac
}

ADRELOAD() {
	case "$1" in
		"ALL")
			shift 1
			ADRELOAD "TMPFS"
			ADRELOAD "CRON"
			ADRELOAD "HAVEGED"
			ADRELOAD "FRANDOM"
			ADRELOAD "ADBLOCK"
			;;
		*)
			ADSTOP "$1"
			ADSTART "$1"
	esac
}

# Initial variables, you should NOT change them unless you know what you're doing
AD="/data/media/0/ArchiDroid"
ADSYS="/system/archidroid"
ADDEV="$ADSYS/dev"
ADTMPFS="$ADSYS/tmpfs"
ADCRON="$ADTMPFS/cron"
LOG="$AD/Init.log" # "/dev/null" is no verbose
#RUNONCELOG="$AD/RunOnce.log" # Unused
ADSTATUS="$ADTMPFS/ARCHIDROID_INIT_STATUS"
ADCRONSTATUS="$ADTMPFS/ARCHIDROID_CRON_STATUS"
INTERNAL_EVENTS_DIR="$ADCRON/events/internal"

# Exit if barebones preset was used
if [[ -f "/system/archidroid/dev/PRESET_BAREBONES" ]]; then
	exit 0
fi

# Exit if user wiped data without reflashing
if [[ ! -f "/data/ARCHIDROID_DONT_REMOVE_ME" ]] ; then
	if ADMOUNTED "/data"; then
		sync
		reboot recovery || poweroff
	else
		# User is probably only charging his device, that's fine
		exit 0
	fi
fi

# Initial ArchiDroid dev status
if [[ -f "$ADDEV/HAVEGED_ENABLED" ]]; then
	HAVEGED=1
else
	HAVEGED=0
fi
if [[ -f "$ADDEV/FRANDOM_ENABLED" ]]; then
	FRANDOM=1
else
	FRANDOM=0
fi
if [[ -f "$ADDEV/ADBLOCK_ENABLED" ]]; then
	ADBLOCK=1
	if [[ -f "$ADDEV/ADBLOCK_LOCAL_DNSES_ENABLED" ]]; then
		ADBLOCKLOCALDNSES=1
		if [[ -f "$ADDEV/ADBLOCK_FORCE_LOCAL_DNSES" ]]; then
			ADBLOCKSTRICTORDER=1
		else
			ADBLOCKSTRICTORDER=0
		fi
	else
		ADBLOCKLOCALDNSES=0
	fi
else
	ADBLOCK=0
fi

if [[ "$1" = "RELOAD" || "$1" = "STOP" || "$1" = "START" ]]; then
	# Allow that regardless of adstatus
	LOG="/dev/null"
	case "$1" in
		"RELOAD") ADRELOAD "$2" ;;
		"START") ADSTART "$2" ;;
		"STOP") ADSTOP "$2" ;;
	esac
	exit 0
elif [[ ! -f "$ADSTATUS" ]]; then
	# First boot, good
	# debuggerd and init.d are executed in the nearly same moment, which may cause typical race condition here
	# It's very likely that these childs will enter this segment in the same moment, we must stop it right here
	# If we're not the lowest PID of all the PIDs from the same process, exit
	if [[ "$(pidof "$(basename "$0")" | awk '{print $1}')" != "$$" ]]; then
		exit 0
	fi
	ADSTART "TMPFS"
	echo "$$" > "$ADSTATUS"
else
	ADSIGNAL="$(cat $ADSTATUS)"
	if [[ "$ADSIGNAL" = "FINISHED" ]]; then
		# Something tried to execute already finished init, halt
		echo "This script has been executed already"
		exit 0
	elif [[ "$ADSIGNAL" = "RESTART" ]]; then
		# Backend restarts itself, good to know, allow that
		echo "$$" > "$ADSTATUS"
	elif [[ -d "/proc/$ADSIGNAL" ]]; then
		# Something tried to execute already running init, double-execution?
		exit 3
	else
		# Old PID is dead and didn't exit properly, allow that for now
		echo "$$" > "$ADSTATUS"
	fi
fi

# Parse args to variables
BACKGROUND=0
for ARG in "$@"; do
	case "$ARG" in
		"background") BACKGROUND=1 ;;
	esac
done

# Now we need to make sure that this is a background process to prevent slowing down bootup
if [[ "$BACKGROUND" -ne 1 ]]; then
	# We're not running in background, let's start a child and tell him that he's running in background
	echo "RESTART" > "$ADSTATUS"
	"$0" "background" "$@" &
	# Nothing to do here anymore, exit call
	exit 0
fi

# Redirect stdout and stderr to our log, just in case something bad happen
if [[ -f "$LOG" ]]; then
	mv "$LOG" "$LOG.old"
fi
exec 1>"$LOG"
exec 2>&1

date
echo "ArchiDroid $(getprop ro.archidroid.version)"
uname -a
echo "INFO: ArchiDroid_Init executed!"

echo "INFO: Waiting for bootanimation..."
LOOP=0
while ! pgrep bootanimation >/dev/null 2>&1 && [[ "$LOOP" -lt 10 ]]; do
	((LOOP++))
	sleep 1
done

if ! pgrep bootanimation >/dev/null 2>&1; then
	echo "INFO: Bootanimation didn't spawn in given period, aborting backend!"
	exit 0
else
	echo "INFO: Bootanimation spawned!"
fi


#   ____
#  / ___| ___   _ __  ___
# | |    / _ \ | '__|/ _ \
# | |___| (_) || |  |  __/
#  \____|\___/ |_|   \___|
#
# Which mode are we using?
# 0 - Sammy
# 1 - CyanogenMod
# 2 - Omni
ROM=0 # Default to sammy
if [[ "$(grep -qi "ro.cm.version" "/system/build.prop"; echo $?)" -eq 0 ]]; then
	ROM=1 # OK, definitely CM
elif [[ "$(grep -qi "ro.omni.version" "/system/build.prop"; echo $?)" -eq 0 ]]; then
	ROM=2 # OK, definitely Omni
fi

# Bring su daemon if available
if [[ ! -z "$(which daemonsu)" ]]; then
	echo "INFO: SuperSU daemon found, calling daemonsu!"
	daemonsu --auto-daemon &
fi

# Custom boot sound support
if [[ -f "$AD/PowerOn.wav" && ! -z "$(which tinyplay)" ]]; then
	tinyplay "$AD/PowerOn.wav" >/dev/null 2>&1 &
fi

# ArchiDroid Hardswap
if [[ "$(busybox swapon --help 2>&1 | grep -qi "\-p pri"; echo $?)" -eq 0 ]]; then
	HSEXTRA="-p 10"
fi
for HSPATH in "/cache" "/preload" "/storage/sdcard1" "/storage/extSdCard"; do
	if [[ -f "$HSPATH/ArchiDroid.swp" ]]; then
		echo "INFO: Found ArchiDroid swap file in $HSPATH directory, $(busybox du -mh "$HSPATH/ArchiDroid.swp" | awk '{print $1}')"
		busybox swapon $HSEXTRA "$HSPATH/ArchiDroid.swp" # Yes, we must break on spaces in this case
	fi
done

# ArchiDroid services
ADSTART "ALL"

# Check if we have LED sysfs available
if [[ -e "/sys/class/leds/led_r/brightness" && -e "/sys/class/leds/led_g/brightness" && -e "/sys/class/leds/led_b/brightness" ]]; then
	LEDS=1
else
	LEDS=0
fi

# ArchiDroid Semaphore
# Wait until we see some android processes to consider boot is more or less complete (initial idea thanks to AndiP71)
# Also respect number of loops, maybe something went wrong
echo "INFO: Init Semaphore started"
LOOP=0
while ! pgrep com.android.systemu >/dev/null 2>&1 && [[ "$LOOP" -lt 600 ]]; do
	((LOOP++))
	if [[ "$LEDS" -ge 1 ]]; then
		while :; do
			case "$LEDS" in
				1) RED=40; GREEN=0; BLUE=0; ;;
				2) RED=40; GREEN=40; BLUE=0 ;;
				3) RED=0; GREEN=40; BLUE=0 ;;
				4) RED=0; GREEN=40; BLUE=40 ;;
				5) RED=0; GREEN=0; BLUE=40 ;;
				6) RED=40; GREEN=0; BLUE=40 ;;
				7) RED=0; GREEN=0; BLUE=0 ;;
				8) LEDS=1; break ;; # This is the last one, so we go back to the start
			esac
			echo "$RED" > "/sys/class/leds/led_r/brightness"
			echo "$GREEN" > "/sys/class/leds/led_g/brightness"
			echo "$BLUE" > "/sys/class/leds/led_b/brightness"
			((LEDS++))
			sleep 0.2
		done
	else
		sleep 1
	fi
done

if [[ "$LOOP" -ge 600 ]]; then
	echo "ERROR: I looped $LOOP times and needed to exit from infinite loop, not good (Init Semaphore)"
else
	echo "INFO: I looped $LOOP times and didn't have to exit from infinite loop, that's nice (Init Semaphore)"
fi

# Execute a reboot if we need it
if [[ -f "$AD/HARD_REBOOT_REQUIRED" ]]; then
	echo "INFO: HARD_REBOOT_REQUIRED found, I'm rebooting device now..."
	rm -f "$AD/SOFT_REBOOT_REQUIRED"
	rm -f "$AD/HARD_REBOOT_REQUIRED"
	if [[ -f "$ADSYS/system/reboot.wav" && ! -z "$(which tinyplay)" ]]; then
		tinyplay "$ADSYS/system/reboot.wav" >/dev/null 2>&1
	fi
	sync
	reboot
elif [[ -f "$AD/SOFT_REBOOT_REQUIRED" ]]; then
	echo "INFO: SOFT_REBOOT_REQUIRED found, I'm rebooting android interface now..."
	rm -f "$AD/SOFT_REBOOT_REQUIRED"
	if [[ -f "$ADSYS/system/reboot.wav" && ! -z "$(which tinyplay)" ]]; then
		tinyplay "$ADSYS/system/reboot.wav" >/dev/null 2>&1 &
	fi
	sync
	setprop ctl.restart surfaceflinger
	setprop ctl.restart zygote
fi

# Wait a little longer
sleep 30

####################################
# We have fully loaded android now #
####################################

# Delete RunOnce if needed
if [[ ! -z "$(which ARCHIDROID_RUNONCE)" ]]; then
	echo "WARNING: RunOnce found, trying to remove it!"
	sysrw || mount -o remount,rw /system
	rm -f "$(which ARCHIDROID_RUNONCE)" "$AD/ARCHIDROID_RUNONCE_STATUS"
	if [[ -z "$(which ARCHIDROID_RUNONCE)" ]]; then
		echo "INFO: Success!"
		sysro || mount -o remount,ro /system
	else
		echo "ERROR: Failed!"
	fi
fi

# Finish
echo "FINISHED" > "$ADSTATUS"
echo "INFO: ArchiDroid Init finished"
date
exit 0
