#!/system/bin/sh

#     _             _     _ ____            _     _
#    / \   _ __ ___| |__ (_)  _ \ _ __ ___ (_) __| |
#   / _ \ | '__/ __| '_ \| | | | | '__/ _ \| |/ _` |
#  / ___ \| | | (__| | | | | |_| | | | (_) | | (_| |
# /_/   \_\_|  \___|_| |_|_|____/|_|  \___/|_|\__,_|
#
# Copyright 2014 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AD="/data/media/0/ArchiDroid"
ADSYS="/system/archidroid"
ADPROC="$ADSYS/tmpfs"
ADCRON="$ADPROC/cron"
LOG="$AD/Cron.log"
MONITORS_DIR="$ADCRON/monitors"
ADSTATUS="$MONITORS_DIR/ARCHIDROID_MONITOR_DNS"

exec 1>>"$LOG"
exec 2>&1
mkdir -p "$MONITORS_DIR"

REGENERATE_RESOLV() {
	echo "nameserver $DNS1" > "$ADPROC/resolv.conf.tmp"
	echo "nameserver $DNS2" >> "$ADPROC/resolv.conf.tmp"
	cat /system/etc/resolv.conf >> "$ADPROC/resolv.conf.tmp"
	busybox chmod 644 "$ADPROC/resolv.conf.tmp"
	mv "$ADPROC/resolv.conf.tmp" "$ADPROC/resolv.conf"
}

MONITOR_DNS() {
	DNS1="$(getprop net.dns1)"
	DNS2="$(getprop net.dns2)"
	local CURDNS1=""
	local CURDNS2=""
	while :; do
		CURDNS1=$(getprop net.dns1)
		if [ "$CURDNS1" != "$DNS1" ]; then
			CURDNS2=$(getprop net.dns2)
			echo "DNS_MONITOR: Detected DNS change, previous: $DNS1 $DNS2, current: $CURDNS1 $CURDNS2"
			DNS1="$CURDNS1"
			DNS2="$CURDNS2"
			REGENERATE_RESOLV
			ARCHIDROID_INIT "RELOAD" "archidroid_dnsproxy2"
		fi
		sleep 2
	done
}

if [ -f "$ADSTATUS" ]; then
	rm -f "$ADSTATUS"
	sleep 1 # If there was a previous instance of the same monitor, give it a time to cleanup and finish
fi

echo "DNS_MONITOR: Active! Current DNSes: $(getprop net.dns1) $(getprop net.dns2)"

MONITOR_DNS &

mkdir -p "$MONITORS_DIR"
echo "$$" > "$ADSTATUS"
inotifywait -qq -e delete -e modify "$ADSTATUS"
echo "DNS_MONITOR: Caught EXIT signal!"
echo "DNS_MONITOR: Finishing..."; kill 0

exit 0