#!/sbin/busybox sh

if [ "a$2" != "a" ];then
filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  if [ "a`eval $evalcmd`" == "a" ];then
    if [ "`cat $2`" == "0" ];then
      eval $filename=off
    else
      eval $filename=on
    fi
  fi
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  if [ -f $2 ];then
    case "$3" in
      off)
        echo 0 > $2
        ;;
      on)
        echo 1 > $2
        ;;
    esac;
  fi
fi
fi


