#!/sbin/busybox sh

echo "$int_scheduler" > /sys/block/mmcblk0/queue/scheduler
echo "$int_read_ahead_kb" > /sys/block/mmcblk0/bdi/read_ahead_kb
echo "$ext_scheduler" > /sys/block/mmcblk1/queue/scheduler
echo "$ext_read_ahead_kb" > /sys/block/mmcblk1/bdi/read_ahead_kb

echo "Scheduler settings applied"

