#!/system/etc/CrossBreeder/busybox sh

set +e

/system/etc/CrossBreeder/busybox start-stop-daemon -o -S -b -x /system/etc/CrossBreeder/zzCrossBreeder &

if [ -x /system/etc/init.d/11link2sd ]; then
 /system/etc/init.d/11link2sd
fi

exec /system/xbin/debuggerd;
