#!/sbin/sh
#Settings: Backup current settings
#Backup current settings of AGNi Control app

TITLE="Backup current settings"
STYLE="Ok"

SYSTEM_DEVICE="/dev/block/mmcblk0p9"
NO_SETTING="0"

# Ask for confirmation
rm /sdcard/boeffla_twk_dlg_helper
am start -a android.intent.action.MAIN -e message "Do you really want to backup your current settings?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Backup settings now!" -e toastn "Backup settings aborted!" -n hm.agni.control.dialog.helper/.AGNiControlDialogActivity

while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/boeffla_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

	# Backup current settings
	/sbin/busybox mkdir -p /data/media/0/AGNi_settings_backup
	/sbin/busybox rm /data/media/0/AGNi_settings_backup/*_001bk*
	/sbin/busybox cp /system/etc/init.d/*_001bk* /data/media/0/AGNi_settings_backup || NO_SETTING="1"
	/sbin/busybox chown -R media_rw:media_rw /data/media/0/AGNi_settings_backup
	/sbin/busybox chmod -R 777 /data/media/0/AGNi_settings_backup

	if [ "$NO_SETTING" = "0" ]; then
		# Display confirmation window
		rm /sdcard/boeffla_twk_dlg_helper
		am start -a android.intent.action.MAIN -e message "Your settings have been saved. You can restore them any time by using the restore function!" -e title "$TITLE" -e okstyle "$STYLE" -n hm.agni.control.dialog.helper/.AGNiControlDialogActivity

		while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
		do
		  /sbin/busybox sleep 1
		done
	fi
	if [ "$NO_SETTING" = "1" ]; then
		rm /sdcard/boeffla_twk_dlg_helper
		am start -a android.intent.action.MAIN -e message "Default Settings Active: nothing to backup. " -e title "$TITLE" -e okstyle "$STYLE" -n hm.agni.control.dialog.helper/.AGNiControlDialogActivity

		while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
		do
		  /sbin/busybox sleep 1
		done
	fi
fi

NO_SETTING="0"
rm /sdcard/boeffla_twk_dlg_helper
