#!/system/bin/sh
#Reboot: CWM Recovery
#Reboot into CWM recovery

TITLE="Reboot: CWM Recovery"

if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
  rm /sdcard/boeffla_twk_dlg_helper
fi;

am start -a android.intent.action.MAIN -e message "Do you want to reboot into CWM recovery now?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toastn "Reboot into CWM recovery aborted!" -n hm.agni.control.dialog.helper/.AGNiControlDialogActivity

while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/boeffla_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

  if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
    rm /sdcard/boeffla_twk_dlg_helper
  fi;

  /sbin/busybox sync
  /sbin/busybox sleep 2s
  /system/bin/reboot recovery

else
  if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
    rm /sdcard/boeffla_twk_dlg_helper
  fi;
  exit 0
fi;
