#!/system/bin/sh -x
echo
echo Please find the debug output to report on forums in /data/cb_CHECK_PROCS.log 
echo
exec 1>/data/cb_CHECK_PROCS.log 2>&1

alias BUSYBOX='/system/etc/CrossBreeder/busybox'

echo -2
echo CrossBreeder Version 6.25.13
echo -1
BUSYBOX uname -a
getprop | BUSYBOX egrep -i "build|product"
echo 0
for i in [1 2 3 4 5]; do cat /proc/sys/kernel/random/entropy_avail; sleep 1; done
echo 0.5
export TZ=GMT; date; stat /proc/sys/kernel/random/write_wakeup_threshold
echo 0.6
BUSYBOX ls -lR /sys/devices/system/cpu/cpu0/cpufreq/
BUSYBOX ls -lR /sys/devices/system/cpu/cpufreq/
GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
BUSYBOX grep '^' /sys/devices/system/cpu/cpu0/cpufreq/$GOVERNOR/*
BUSYBOX grep '^' /sys/devices/system/cpu/cpufreq/$GOVERNOR/*
echo 1
BUSYBOX ps -o pid,ppid,user,etime,nice,vsz,rss,args | BUSYBOX egrep -i "USER|wake|sleep|zz|haveged|dnrd|thttp|busybox|dns|CB|rinet|pixel|kworker"
echo 2
toolbox ps -p | BUSYBOX egrep -i "USER|wake|sleep|zz|haveged|dnrd|thttp|busybox|dns|CB|rinet|pixel|kworker"
echo 3
BUSYBOX ps w | BUSYBOX egrep -i "USER|wake|sleep|zz|haveged|dnrd|thttp|busybox|dns|CB|rinet|pixel|kworker"
echo 4
BUSYBOX top -b -n 5 -d 1 | BUSYBOX egrep -i "USER|wake|sleep|zz|haveged|dnrd|thttp|busybox|dns|CB|rinet|pixel|kworker"
echo 5
( getprop | BUSYBOX grep dns ) &
echo 6
BUSYBOX time /system/etc/CrossBreeder/dnsc &
BUSYBOX time /system/etc/CrossBreeder/dnsc 127.0.0.3 www.microsoft.com 10053 &
BUSYBOX time /system/etc/CrossBreeder/dnsc 8.8.8.8 www.microsoft.com &
BUSYBOX time /system/etc/CrossBreeder/dnsc 8.8.4.4 www.microsoft.com &
BUSYBOX time /system/etc/CrossBreeder/dnsc 209.244.0.4 www.microsoft.com &
BUSYBOX time /system/etc/CrossBreeder/dnsc 209.244.0.3 www.microsoft.com &

BUSYBOX netstat -an | BUSYBOX grep -i LISTEN
BUSYBOX netstat -an | BUSYBOX egrep "53|54|67"
echo 6.1
BUSYBOX timeout -t 3 -s KILL logcat | BUSYBOX grep -i dns
echo 7
cat /data/dnsmasq.log
echo 7.1
cat /data/dnsmasq.leases
echo 7.2
cat /dev/dnrd.log
echo 7.3
cat /dev/resolv-local.conf
echo 7.4
cat /system/etc/CrossBreeder/REMOTE_DNS
echo 7.5
cat /system/etc/CrossBreeder/ENTROPY_FEED_FREQUENCY_SECS
echo 7.6
cat /system/etc/CrossBreeder/IRQ_FLUSH_FREQUENCY_MINUTES
echo 7.7
cat /system/etc/CrossBreeder/WRITE_WAKEUP_THRESHOLD
echo 8
ls -l /system/etc/init.d/
echo 9
ls -l /system/etc/
echo 9.1
cat /system/etc/install-recovery.sh
echo 9.2
cat /system/etc/hw_config.sh
echo 9.3
cat /system/etc/hw_config.sh.CBBAK
echo 9.4
ls -l /system/etc/hw_config*
echo 10 
ls -l /system/bin/debuggerd*
echo 11
ls -l /system/bin/dnsmasq*
echo 12
ls -l /data/CrossBreeder*
echo 12.1
BUSYBOX ls -l /etc/CrossBreeder/
echo 13
BUSYBOX time ping -c 3 www.google.com
echo 14
BUSYBOX time /system/etc/CrossBreeder/busybox ping -c 3 www.google.com
echo 15
cat /etc/resolv.conf
echo 16
cat /etc/dnsmasq.conf
echo 17
ls -l /etc/hosts
echo 18
ls -l /dev/*dom*
echo 19
BUSYBOX lsof | grep -i dom
echo 20
cat /init.rc
echo 21
/system/etc/CrossBreeder/busybox sh -x /system/etc/CrossBreeder/zzCrossBreeder FORCE
echo 22
cat /system/build.prop
echo 23
/system/etc/CrossBreeder/sqlite3 /data/data/com.android.providers.settings/databases/settings.db 'select * from global;'
echo 24
/system/etc/CrossBreeder/sqlite3 /data/data/com.android.providers.settings/databases/settings.db 'select * from system;'
echo 25
cat /data/recovery_cb.log 
echo 26
cat /cache/recovery/last_log
echo 27
cat /proc/last_kmsg
