#!/system/etc/CrossBreeder/busybox sh 
set +e

/system/etc/CrossBreeder/busybox mount -o rw,remount,noatime,nodiratime /system

touch /system/etc/CrossBreeder/STOP_TWEAKING_GOVERNOR 2>/dev/null
rm /system/etc/CrossBreeder/START_TWEAKING_GOVERNOR 2>/dev/null

/system/etc/CrossBreeder/busybox mount -o ro,remount,noatime,nodiratime /system

echo DONE. Governor tweaks are disabled. This requires reboot to take effect.
