#!/system/etc/CrossBreeder/busybox sh 
set +e

/system/etc/CrossBreeder/busybox mount -o rw,remount,noatime,nodiratime /system

touch /system/etc/CrossBreeder/START_TWEAKING_IO 2>/dev/null

/system/etc/CrossBreeder/busybox mount -o ro,remount,noatime,nodiratime /system

/system/etc/CrossBreeder/zzCrossBreeder FORCE &

echo DONE. IO tweaks are enabled and in effect.
