#!/system/bin/sh
export PATH=/system/etc/CrossBreeder:$PATH
 
busybox mount -o rw,remount,noatime,nodiratime /system 2>/dev/null
 
rm /system/etc/CrossBreeder/STOP_DNS 2>/dev/null

if [ -f /system/etc/CrossBreeder/dnsmasq.txt ]; then
 if [ ! -f /system/bin/dnsmasq.CBBAK ]; then 
  if [ "`dd if=/system/bin/dnsmasq skip=1 bs=1 count=3 2>/dev/null`" = "ELF" ]; then
    busybox cp -f /system/bin/dnsmasq /system/bin/dnsmasq.CBBAK
  else 
    busybox cp -f /system/bin/dnsmasq_dhcp /system/bin/dnsmasq.CBBAK
  fi
 fi
 busybox cp -f /system/etc/CrossBreeder/dnsmasq.txt /system/bin/dnsmasq
 chmod 755 /system/bin/dnsmasq
fi
 
busybox mount -o ro,remount,noatime,nodiratime /system 2>/dev/null
 
echo DONE. Please reboot your device now.
