#!/system/bin/sh
export PATH=/system/etc/CrossBreeder:$PATH

busybox mount -o rw,remount,noatime,nodiratime /system

touch /system/etc/CrossBreeder/STOP_DNS

if [ -f /system/bin/dnsmasq.CBBAK ]; then 
  busybox cp -a /system/bin/dnsmasq.CBBAK /system/bin/dnsmasq
  chmod 755 /system/bin/dnsmasq
else
  if [ ! "`dd if=/system/bin/dnsmasq skip=1 bs=1 count=3 2>/dev/null`" = "ELF" ]; then
    busybox cp -a /system/bin/dnsmasq_dhcp /system/bin/dnsmasq
  fi
fi

busybox mount -o rw,remount,noatime,nodiratime /system

killall -9 dnrd.10053

echo DONE. Please reboot your device now.
