#!/system/bin/sh
export PATH=/system/etc/CrossBreeder:$PATH

busybox mount -o rw,remount,noatime,nodiratime /system

if [ -f /system/bin/dnsmasq_dhcp ]; then 
  busybox cp -a /system/bin/dnsmasq_dhcp /system/bin/dnsmasq
  chmod 755 /system/bin/dnsmasq
fi

busybox mount -o rw,remount,noatime,nodiratime /system

echo DONE. Please reboot your device now.
