#!/system/etc/CrossBreeder/busybox sh
set +e
export PATH=/system/etc/CrossBreeder:$PATH:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
alias BUSYBOX='/system/etc/CrossBreeder/busybox'

dns2=$(getprop net.dns2 2>/dev/null)

  if [ "x$dns2" = "x" ]; then dns2="8.8.8.8"; fi

  olddns1=`BUSYBOX awk '{ print $2 }' /dev/resolv-local.conf 2>/dev/null | BUSYBOX sed -e '$!{h;d;}' -e x 2>/dev/null`
  if [ "x$olddns1" = "x" ]; then
    olddns1=$dns2
  fi
  setprop net.dns1 $olddns1

  olddns2=`BUSYBOX awk '{ print $2 }' /dev/resolv-local.conf 2>/dev/null| BUSYBOX tail -1 2>/dev/null`
  if [ "x$olddns2" = "x" ]; then
    olddns2="208.67.220.220"
  fi;
  setprop net.dns2 $olddns2

  setprop ro.kernel.android.ndns 2
  setprop net.change net.dnschange
  setprop net.dnschange $(($(getprop net.dnschange) + 1));

