#!/system/bin/sh

# ArchiDroid SQLite VACUUM
# JustArchi@JustArchi.net

# Not Disabled
#exit 0

AD="/data/media/0/ArchiDroid"
LOG="$AD/SQLite.log" # "/dev/null" is no verbose

# Redirect stderr and stdout to our log, just in case something bad happen
exec 1>$LOG # Use "exec 1>>$LOG" for append
exec 2>&1

echo "INFO: SQLite database VACUUM and REINDEX started at `date`"
for i in `busybox find /data -iname "*.db"`; do
	echo "INFO: VACUUM & REINDEX $i"
	/system/xbin/sqlite3 $i 'VACUUM;';
	/system/xbin/sqlite3 $i 'REINDEX;';
done
echo "INFO: SQLite database VACUUM and REINDEX finished at `date`"
exit 0