#!/system/bin/sh

# ArchiDroid Zipalign Script
# JustArchi@JustArchi.net

# Not Disabled
#exit 0

# Initial variables, you should NOT change them unless you know what you're doing
AD="/data/media/0/ArchiDroid"
LOG="$AD/Zipalign.log" # "/dev/null" is no verbose

# Redirect stderr and stdout to our log, just in case something bad happen
exec 1>$LOG # Use "exec 1>>$LOG" for append
exec 2>&1

echo "INFO: Starting Automatic ZipAlign at `date`"
for apk in /data/app/*.apk ; do
	zipalign -c 4 $apk;
	ZIPCHECK=$?;
	if [ $ZIPCHECK -eq 1 ]; then
		echo "INFO: ZipAligning $(basename $apk)"
		zipalign -f 4 $apk /cache/$(basename $apk);
		if [ -e /cache/$(basename $apk) ]; then
			cp -f -p /cache/$(basename $apk) $apk  | tee -a $LOG_FILE;
			rm /cache/$(basename $apk);
		else
			echo "ERROR: ZipAligning $(basename $apk) Failed"
		fi
	else
		echo "INFO: ZipAlign already completed on $apk"
	fi
done
echo "INFO: Automatic ZipAlign finished at `date`"
exit 0