#!/system/bin/sh

# ArchiDroid FIRSTBOOT Script
# JustArchi@JustArchi.net

# Not Disabled
#exit 0

# We don't want to force anything in update mode
FORCE=0

DBUPDATE() {
	# Thanks to idcrisis, modified by JustArchi
	WHAT=$1
	VARIABLE=$2
	VAL=$3
	DONE=0
	TRY=0
	SQLITE3='/system/xbin/sqlite3'

	while [ $DONE -ne 1 ] ; do
		((TRY++))
		# Try to update value first if exists
		busybox sync
		CHECK=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "update $WHAT set value='$VAL' where name='$VARIABLE';" 2>/dev/null`
		busybox sync
		
		# See if it worked
		VAL1=""
		VAL1=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "select value from $WHAT where name='$VARIABLE';" 2>/dev/null`
		
		# If not create it
		if [ "$VAL1" != "" ]; then
			# Looks good
			DONE=1
			return 0
		else
			#ID=""
			#ID=`sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select max(_id)+100 from $WHAT;"`
			#if [ "$ID" == "" ]; then 
			#	ID='null'
			#fi
			ID='null'

			CHECK=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "insert into $WHAT values($ID, '$VARIABLE', '$VAL');" 2>/dev/null`
			busybox sync
		fi
		
		# Check if in fact we modified that
		VAL1=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "select value from $WHAT where name='$VARIABLE';" 2>/dev/null`
		if [ "$VAL1" != "" ]; then
			# Looks good
			DONE=1
			return 0
		else
			# We failed, let's try maximum of 3 times before giving up
			echo "ArchiDroid_RunOnce: DBUPDATE() FAILED with $WHAT $VARIABLE $VAL. Check returned $CHECK. This is our $TRY try" >> /data/media/0/ArchiDroid/err.log
			sleep 1
			if [ $TRY -ge 3 ]; then
				echo "ArchiDroid_RunOnce: Sorry master, I'm giving up. Something is definitely broken here!" >> /data/media/0/ArchiDroid/err.log
				DONE=1
				return 1
			fi
		fi
	done
}

# Make sure that our folder is still here
if [ ! -d /data/media/0/ArchiDroid ]; then
	mkdir -p /data/media/0/ArchiDroid
fi

# Now we need to make sure that this is background process to prevent slowing down bootup
if [ ! -e /data/media/0/ArchiDroid/RUNONCE_BACKGROUND ]; then
	# We're not running in background, let's start a child and tell him that he's running in background
	touch /data/media/0/ArchiDroid/RUNONCE_BACKGROUND
	sh $0 &
	
	# Nothing to do here anymore, exit call
	exit 1
else
	# We're running in background so let's proceed
	rm -f /data/media/0/ArchiDroid/RUNONCE_BACKGROUND
fi

# We don't need to reload anything for now
ADRELOAD=0

# Cool ArchiDroid Banner
if [ -e /system/bin/boot-dmesg ]; then
	ADBANNER=1
else
	ADBANNER=0
fi

# We want some sqlite3 updates and settings but only if INSTALL mode is enabled
if [ -e /data/media/0/ArchiDroid/INSTALL ] || [ $FORCE -eq 1 ]; then
	if [ -d /data/media/0/ArchiDroid/FIRSTBOOT/DATA ]; then
		cd /data/media/0/ArchiDroid/FIRSTBOOT/DATA
		ADMANY=`ls | wc -l`
	fi
	DBUPDATE=1
	ADRELOAD=1
elif [ -e /data/media/0/ArchiDroid/UPDATE ]; then
	DBUPDATE=0
	ADMANY=0
else
	# Panic
	exit 1
fi

# ArchiDroid Semaphore
# Wait until we see some android processes to consider boot is more or less complete (credits to AndiP71)
# Also respect number of loops, maybe something went wrong
LOOP=0
while ! pgrep com.android && [ $LOOP -lt 150 ] ; do

	if [ $ADBANNER -eq 1 ]; then
		echo ""
		echo "*******************************************************************************"
		echo "*             _                _      _  ____               _      _          *"
		echo "*            / \    _ __  ___ | |__  (_)|  _ \  _ __  ___  (_)  __| |         *"
		echo "*           / _ \  | '__|/ __|| '_ \ | || | | || '__|/ _ \ | | / _\` |         *"
		echo "*          / ___ \ | |  | (__ | | | || || |_| || |  | (_) || || (_| |         *"
		echo "*         /_/   \_\|_|   \___||_| |_||_||____/ |_|   \___/ |_| \__,_|         *"
		echo "*                                                                             *"
		echo "*******************************************************************************"
		echo "*                  _                       _  _                               *"
		echo "*                 | |     ___    __ _   __| |(_) _ __    __ _                 *"
		echo "*                 | |    / _ \  / _\` | / _\` || || '_ \  / _\` |                *"
		echo "*                 | |___| (_) || (_| || (_| || || | | || (_| |                *"
		echo "*                 |_____|\___/  \__,_| \__,_||_||_| |_| \__, |                *"
		echo "*                                                       |___/                 *"
		echo "*******************************************************************************"
		echo "*            root@ArchiDroid:~# Waiting for ArchiDroid to load...             *"
		echo "*******************************************************************************"
		echo ""
	fi
	
	if [ $DBUPDATE -eq 1 ]; then
		if [ -e /data/data/com.android.providers.settings/databases/settings.db ]; then
			DBUPDATE secure advanced_reboot 1
			DBUPDATE global transition_animation_scale 0.5
			DBUPDATE global animator_duration_scale 0.5
			DBUPDATE global window_animation_scale 0.5
			DBUPDATE global wifi_scan_always_enabled 0
			DBUPDATE global install_non_market_apps 1
			DBUPDATE system power_menu_screenshot_enabled 1
			DBUPDATE system status_bar_battery 3
			DBUPDATE system statusbar_clock_date_display 2
			DBUPDATE system statusbar_clock_date_format 'MMM dd'
			DBUPDATE system status_bar_traffic 0
			
			# And don't execute twice
			DBUPDATE=0
		fi
	fi
	
	# Now let's MAKE SURE that our settings are in fact applied, only if we don't have shared_prefs already (prevent non-clean override)
	if [ $ADMANY -gt 0 ]; then
		cd /data/media/0/ArchiDroid/FIRSTBOOT/DATA
		for FOLDER in * ; do
			if [ -d /data/data/$FOLDER ]; then
				mv $FOLDER/* /data/data/$FOLDER

				# Let's set basic permissions because ArchiDroid_Permfix will fix it anyway really soon
				ADOWNER=`ls -ld /data/data/$FOLDER | awk '{print $3}'`
				busybox chown -hR $ADOWNER.$ADOWNER /data/data/$FOLDER
				busybox chmod -R 755 /data/data/$FOLDER

				# And we're done!
				rm -Rf $FOLDER
				ADOWNER=""
				ADMANY=`ls | wc -l`
			fi
		done
		#ADMANY=`ls | wc -l`
	fi

	# Sleeping time
	((LOOP++))
	sleep 2
done

if [ $LOOP -ge 150 ]; then
	echo "ArchiDroid_RunOnce: LOOP() FAILED. I looped $LOOP times and needed to exit from infinite loop, not good" >> /data/media/0/ArchiDroid/err.log
fi

# Now that is checked, let's just wait another tiny little bit
sleep 5

# If we have any more runonce scripts then it's the right place for that

# IMPORTANT, CrossBreeder's Adblock doesn't work properly with Android 4.3 for now, fall back to AdAway version until it's fixed.
if [ -d /system/etc/CrossBreeder ]; then
	sh /system/etc/CrossBreeder/DISABLE_ADBLOCK
	sysrw
	cat /system/etc/ahosts > /system/etc/hosts
	sysro
	ADRELOAD=1
fi

# I'm runonce script so let's clean everything and delete myself

# NOTICE
# ArchiDroid has sysro/sysrw support, change that to remount system rw if needed
rm -f /data/media/0/ArchiDroid/INSTALL
rm -f /data/media/0/ArchiDroid/UPDATE
rm -Rf /data/media/0/ArchiDroid/FIRSTBOOT
rm -Rf /data/media/0/vrtheme-backup
sysrw
rm -f $0
sysro

# Execute hot reboot if we need it
if [ $ADRELOAD -eq 1 ]; then
	killall system_server
fi

# Finish
exit 0