#!/system/bin/sh
#Microphone sensivity general
#Set microphone sensivity for recording purposes
#30db

echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound
echo 31 > /sys/class/misc/boeffla_sound/mic_level_general
