#!/system/bin/sh
#Microphone sensivity call
#Set microphone sensivity for calls
#21db (default)

echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound
echo 25 > /sys/class/misc/boeffla_sound/mic_level_call
