#!/system/bin/sh
export PATH=/system/etc/CrossBreeder:$PATH:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
exec 0>&1

set +e
 
busybox mount -o rw,remount /system

#if [ ! -f /system/etc/dnsmasq.conf.CBBAK ]; then 
#  rm /system/etc/dnsmasq.conf
#else
  busybox mv -f /system/etc/dnsmasq.conf.CBBAK /system/etc/dnsmasq.conf 2>/dev/null
#fi

busybox sed -i -e "/.*CrossBreeder.*/d" /system/etc/dnsmasq.conf 2>/dev/null
busybox sed -i -e "/.*dnsmasq-local.*/d" /system/etc/dnsmasq.conf 2>/dev/null

#if [ "`cat /system/etc/dnsmasq.conf 2>/dev/null | wc -l 2>/dev/null`" = "0" ]; then rm /system/etc/dnsmasq.conf; fi

touch /system/etc/dnsmasq.conf

#echo conf-file=/data/dnsmasq-local.conf >> /system/etc/dnsmasq.conf

busybox mount -o ro,remount /system

echo DONE. Please reboot your device now.
