#!/sbin/busybox sh
#Touchboost
#Enable or disable Touchboost:
#400 MHz

echo "1" > /sys/class/misc/touchboost_switch/touchboost_switch
echo "400000" > /sys/class/misc/touchboost_switch/touchboost_freq

