#!/sbin/busybox sh
#Touch Wake
#Enable or disable Touch to Wake:
#KnockON 10 sec

echo "1" > /sys/class/misc/touchwake/enabled
echo "10" > /sys/class/misc/touchwake/delay

echo "1" > /sys/class/misc/touchwake/knockon
echo "180" > /sys/class/misc/touchwake/charging_delay
echo "1" > /sys/class/misc/touchwake/keypower_mode

